create table if not exists public.parent_players (
  id integer generated by default as identity primary key,
  academy_id integer,
  parent_user_id integer not null,
  player_id integer not null,
  created_by integer,
  created_at timestamp without time zone default now()
);

create unique index if not exists idx_parent_players_unique_link
on public.parent_players (parent_user_id, player_id);

create index if not exists idx_parent_players_parent
on public.parent_players (academy_id, parent_user_id);

create index if not exists idx_parent_players_player
on public.parent_players (academy_id, player_id);
