begin;

create table if not exists public.fitness_test_definitions (
  id integer generated by default as identity primary key,
  academy_id integer,
  test_name character varying not null,
  metric_type character varying not null,
  unit character varying,
  lower_is_better boolean default false,
  is_active boolean default true,
  max_attempts integer default 8,
  created_by integer,
  created_at timestamp without time zone default now()
);

create table if not exists public.fitness_test_sessions (
  id integer generated by default as identity primary key,
  academy_id integer,
  test_id integer not null,
  session_date date not null,
  attempt_count integer not null default 1,
  created_by integer,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

alter table public.fitness_test_definitions
  add column if not exists max_attempts integer default 8;

update public.fitness_test_definitions
set max_attempts = 8
where max_attempts is null or max_attempts <= 0;

create table if not exists public.player_fitness_test_records (
  id integer generated by default as identity primary key,
  academy_id integer,
  player_id integer,
  test_id integer,
  measured_on date not null default current_date,
  attempt_number integer not null default 1,
  result_value numeric(10,2) not null,
  notes text,
  created_by integer,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

alter table public.player_fitness_test_records
  add column if not exists attempt_number integer default 1;

update public.player_fitness_test_records
set attempt_number = 1
where attempt_number is null or attempt_number <= 0;

alter table public.player_fitness_test_records
  alter column attempt_number set not null;

drop index if exists idx_player_fitness_test_records_unique_day;

create unique index if not exists idx_fitness_test_definitions_academy_name
on public.fitness_test_definitions (academy_id, lower(test_name));

create unique index if not exists idx_fitness_test_sessions_unique_day
on public.fitness_test_sessions (academy_id, test_id, session_date);

create index if not exists idx_fitness_test_sessions_test_date
on public.fitness_test_sessions (academy_id, test_id, session_date desc);

create unique index if not exists idx_player_fitness_test_records_unique_attempt
on public.player_fitness_test_records (academy_id, player_id, test_id, measured_on, attempt_number);

create index if not exists idx_player_fitness_test_records_player_test_date
on public.player_fitness_test_records (academy_id, player_id, test_id, measured_on desc, attempt_number asc, id desc);

create index if not exists idx_player_fitness_test_records_test_date
on public.player_fitness_test_records (academy_id, test_id, measured_on desc, attempt_number asc);

insert into public.fitness_test_sessions (
  academy_id,
  test_id,
  session_date,
  attempt_count
)
select
  records.academy_id,
  records.test_id,
  records.measured_on,
  greatest(max(records.attempt_number), 1) as attempt_count
from public.player_fitness_test_records records
group by records.academy_id, records.test_id, records.measured_on
on conflict (academy_id, test_id, session_date) do update
set attempt_count = excluded.attempt_count,
    updated_at = now();

insert into public.fitness_test_definitions (
  academy_id,
  test_name,
  metric_type,
  unit,
  lower_is_better,
  is_active,
  max_attempts
)
select academies.id, defaults.test_name, defaults.metric_type, defaults.unit, defaults.lower_is_better, true, defaults.max_attempts
from public.academies academies
cross join (
  values
    ('100m Sprint', 'time', 'sec', true, 8),
    ('200m Sprint', 'time', 'sec', true, 8),
    ('400m Run', 'time', 'sec', true, 6),
    ('Shuttle Run', 'time', 'sec', true, 6),
    ('Standing Broad Jump', 'distance', 'cm', false, 6),
    ('Vertical Jump', 'distance', 'cm', false, 6)
) as defaults(test_name, metric_type, unit, lower_is_better, max_attempts)
where not exists (
  select 1
  from public.fitness_test_definitions existing
  where existing.academy_id = academies.id
    and lower(existing.test_name) = lower(defaults.test_name)
);

commit;
