begin;

create table if not exists public.academy_match_results (
  id integer generated by default as identity primary key,
  academy_id integer,
  category_id integer,
  match_date date not null,
  player1_id integer not null,
  player2_id integer not null,
  result_type character varying not null default 'normal',
  score_raw text,
  winner_id integer not null,
  notes text,
  created_by integer,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

alter table public.academy_match_results
  add column if not exists result_type character varying not null default 'normal';

alter table public.academy_match_results
  alter column score_raw drop not null;

update public.academy_match_results
set result_type = coalesce(nullif(result_type, ''), 'normal')
where result_type is null or result_type = '';

create unique index if not exists idx_academy_match_results_unique_pair
on public.academy_match_results (
  academy_id,
  category_id,
  match_date,
  player1_id,
  player2_id
);

create index if not exists idx_academy_match_results_category_date
on public.academy_match_results (academy_id, category_id, match_date desc);

create index if not exists idx_academy_match_results_players
on public.academy_match_results (academy_id, player1_id, player2_id, match_date desc);

commit;
