begin;

alter table if exists public.batch_sessions
  add column if not exists session_date date,
  add column if not exists notes text,
  add column if not exists status character varying;

update public.batch_sessions
set session_date = coalesce(session_date, created_at::date)
where session_date is null;

update public.batch_sessions
set status = coalesce(nullif(status, ''), 'scheduled')
where status is null or status = '';

create table if not exists public.attendance_records (
  id integer generated by default as identity primary key,
  academy_id integer,
  session_id integer,
  player_id integer,
  status character varying not null,
  notes text,
  marked_by integer,
  marked_at timestamp without time zone default now(),
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

create unique index if not exists idx_attendance_records_session_player
on public.attendance_records (session_id, player_id);

create index if not exists idx_attendance_records_academy_session
on public.attendance_records (academy_id, session_id);

create index if not exists idx_batch_sessions_batch_date
on public.batch_sessions (academy_id, batch_id, session_date);

commit;
